language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  
  - "nightly"  
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - echo "skipping tests"
