language: python
python:
  - "3.6"
  - "3.6-dev"  
  - "3.7-dev"
  - "3.8" 
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - echo "skipping tests"
